# Generated by Django 4.0.5 on 2022-06-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='Some String', max_length=250, verbose_name='Название'),
        ),
    ]
